/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Student = {
  /**
   * The main identifying information for the student, typically their full name.
   */
  mainItem: string;
  /**
   * An array of key-value pairs representing other information from the spreadsheet.
   */
  subItems: {
    label: string;
    value: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
};
export type User = {
  /**
   * A map of FCM registration tokens for the user's devices. The keys are the tokens.
   */
  fcmTokens?: {
    [k: string]: boolean;
  };
  [k: string]: unknown;
};
